## **Importing Libraries** ##

In [42]:
import pandas as pd
import numpy as np

# **Choose dataset from local directory**

In [43]:
from google.colab import files
uploaded = files.upload()

Saving Salary_Data1.csv to Salary_Data1.csv


# **Load Dataset**

In [45]:
dataset=pd.read_csv('Salary_Data1.csv')
print(dataset)

     Age  Salary  Status
0   21.0   39343       0
1   21.5   46205       0
2   21.7   37731       0
3   22.0   43525       1
4   22.2   39891       0
5   23.0   56642       1
6   23.0   60150       1
7   23.3   54445       1
8   23.3   64445       0
9   23.6   57189       1
10  23.9   63218       0
11  24.0   55794       1
12  24.0   56957       1
13  24.0   57081       1
14  25.0   61111       1
15  25.0   67938       0
16  26.0   66029       1
17  27.0   83088       1
18  28.0   81363       0
19  29.0   93940       1
20  30.0   91738       0
21  30.0   98273       1
22  31.0  101302       1
23  32.0  113812       0
24  33.0  109431       1
25  34.0  105582       1
26  35.0  116969       1
27  36.0  112635       1
28  37.0  122391       0
29  38.0  121872       1


# **Summarize Dataset**

In [46]:
print(dataset.shape)
print(dataset.head(5))

(30, 3)
    Age  Salary  Status
0  21.0   39343       0
1  21.5   46205       0
2  21.7   37731       0
3  22.0   43525       1
4  22.2   39891       0


# **Segregate Dataset into X(Input/Independent Variable) & Y(Output/Dependent Variable)**

In [47]:
X = dataset.iloc[:,:-1].values
X

array([[2.10000e+01, 3.93430e+04],
       [2.15000e+01, 4.62050e+04],
       [2.17000e+01, 3.77310e+04],
       [2.20000e+01, 4.35250e+04],
       [2.22000e+01, 3.98910e+04],
       [2.30000e+01, 5.66420e+04],
       [2.30000e+01, 6.01500e+04],
       [2.33000e+01, 5.44450e+04],
       [2.33000e+01, 6.44450e+04],
       [2.36000e+01, 5.71890e+04],
       [2.39000e+01, 6.32180e+04],
       [2.40000e+01, 5.57940e+04],
       [2.40000e+01, 5.69570e+04],
       [2.40000e+01, 5.70810e+04],
       [2.50000e+01, 6.11110e+04],
       [2.50000e+01, 6.79380e+04],
       [2.60000e+01, 6.60290e+04],
       [2.70000e+01, 8.30880e+04],
       [2.80000e+01, 8.13630e+04],
       [2.90000e+01, 9.39400e+04],
       [3.00000e+01, 9.17380e+04],
       [3.00000e+01, 9.82730e+04],
       [3.10000e+01, 1.01302e+05],
       [3.20000e+01, 1.13812e+05],
       [3.30000e+01, 1.09431e+05],
       [3.40000e+01, 1.05582e+05],
       [3.50000e+01, 1.16969e+05],
       [3.60000e+01, 1.12635e+05],
       [3.70000e+01,

In [48]:
Y=dataset.iloc[:,-1].values
Y

array([0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1])

# **Spliting Dataset into Train & Test**

In [60]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.05,random_state=42)

# **Feature Scaling**

In [61]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
print(X_train)

[[ 1.01160874  1.43999514]
 [ 0.00360003  0.30058579]
 [-0.74232642 -0.39079582]
 [-0.68184589 -0.6598869 ]
 [ 2.01961746  1.75815009]
 [ 1.21321049  1.27752435]
 [-0.6012052  -0.6684907 ]
 [-1.20601042 -1.32171151]
 [-0.96408833 -1.30138876]
 [-0.19800171 -0.33205268]
 [-0.80280694 -0.68017257]
 [-0.6012052  -0.66389212]
 [-0.6012052  -0.71162092]
 [ 0.810007    0.97605779]
 [-1.10520955 -1.06723205]
 [-1.0648892  -1.38149305]
 [ 1.41481223  1.13478296]
 [-1.00440868 -1.16662071]
 [ 0.60840526  0.86372636]
 [ 1.61641397  1.55707349]
 [ 0.20520177  0.23661361]
 [ 2.2212192   1.73890281]
 [ 0.60840526  0.6213738 ]
 [-0.74232642 -0.76164902]
 [-0.62136537 -0.43629951]
 [-0.39960345 -0.51443828]
 [ 0.40680352  0.70303567]
 [-0.80280694 -0.55007727]]


# **Training**

In [62]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state=0)
model.fit(X_train,Y_train)

LogisticRegression(random_state=0)

# **Prediction**

In [63]:
age=int(input("Enter age:"))
sal=float(input("Enter exp:"))
newEmp =[[age,sal]]
result=model.predict(sc.transform(newEmp))
print(f"Salary should be : {result}"  )


Enter age:20
Enter exp:40000
Salary should be : [1]


# **Prediction for all test data**

In [64]:
Y_pred=model.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1),Y_test.reshape(len(Y_test),1)),1))

[[1 1]
 [1 0]]


# **Accuracy**

In [59]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,Y_pred)

0.5